
---
# Default Connectivity Variables used by any/all groups, overridden only by the group specific variables.

ansible_user: "admin"
ansible_ssh_pass: "cisco"
ansible_network_os: "ios"
ansible_connection: "network_cli"
ansibe_become: yes
ansible_become_password: "cisco"

ntp_server: 1.1.1.1

domain_name: ansible.local
name_servers:
  #server1: 8.8.8.8
  #server2: 9.9.9.9
  - 8.8.8.8
  - 9.9.9.9
  - 10.10.10.10

interfaces:
 CSR-1:
  - name: GigabitEthernet1
    description: to_CSR-2_Gig1
  - name: GigabitEthernet2
    description: to_CSR-3_Gig1
  - name: GigabitEthernet3
    description: to_CSR-4_Gig1
 CSR-2:
  - name: GigabitEthernet1
    description: to_CSR-1_Gig1
  - name: GigabitEthernet2
    description: to_CSR-3_Gig1
  - name: GigabitEthernet3
    description: to_CSR-4_Gig1
 CSR-3:
  - name: GigabitEthernet1
    description: to_CSR-1_Gig1
  - name: GigabitEthernet2
    description: to_CSR-2_Gig1
  - name: GigabitEthernet3
    description: to_CSR-4_Gig1
 CSR-4:
  - name: GigabitEthernet1
    description: to_CSR-1_Gig1
  - name: GigabitEthernet2
    description: to_CSR-2_Gig1
  - name: GigabitEthernet3
    description: to_CSR-3_Gig1

intf_duplex: full
intf_mtu: 1500

l3_interfaces:
 CSR-1:
  - name: GigabitEthernet1
    ipv4: 172.16.12.1/30
  - name: GigabitEthernet2
    ipv4: 172.16.13.1/30
  - name: GigabitEthernet3
    ipv4: 172.16.14.1/30
 CSR-2:
  - name: GigabitEthernet1
    ipv4: 172.16.12.2/30
  - name: GigabitEthernet2
    ipv4: 172.16.23.1/30
  - name: GigabitEthernet3
    ipv4: 172.16.24.1/30
 CSR-3:
  - name: GigabitEthernet1
    ipv4: 172.16.13.2/30
  - name: GigabitEthernet2
    ipv4: 172.16.23.2/30
  - name: GigabitEthernet3
    ipv4: 172.16.34.1/30
 CSR-4:
  - name: GigabitEthernet1
    ipv4: 172.16.14.2/30
  - name: GigabitEthernet2
    ipv4: 172.16.24.2/30
  - name: GigabitEthernet3
    ipv4: 172.16.34.2/30

l3:
  CSR-1:
      GigabitEthernet1: 172.16.12.1/30
      GigabitEthernet2: 172.16.13.1/30
      GigabitEthernet3: 172.16.14.1/30