
---
# Default Connectivity Variables used by any/all groups, overridden only by the group specific variables.

ansible_user: "admin"
ansible_ssh_pass: "cisco"
ansible_network_os: "ios"
ansible_connection: "network_cli"
ansibe_become: yes
ansible_become_password: "cisco"

ntp_server: 1.1.1.1

domain_name: ansible.local
name_servers:
  #server1: 8.8.8.8
  #server2: 9.9.9.9
  - 8.8.8.8
  - 9.9.9.9
  - 10.10.10.10

interfaces:
 CSR_1:
  - name: GigabitEthernet1
    description: to_CSR-2_Gig1
  - name: GigabitEthernet2
    description: to_CSR-3_Gig1
  - name: GigabitEthernet3
    description: to_CSR-4_Gig1
 CSR_2:
  - name: GigabitEthernet1
    description: to_CSR-1_Gig1
  - name: GigabitEthernet2
    description: to_CSR-3_Gig1
  - name: GigabitEthernet3
    description: to_CSR-4_Gig1
 CSR_3:
  - name: GigabitEthernet1
    description: to_CSR-1_Gig1
  - name: GigabitEthernet2
    description: to_CSR-2_Gig1
  - name: GigabitEthernet3
    description: to_CSR-4_Gig1
 CSR_4:
  - name: GigabitEthernet1
    description: to_CSR-1_Gig1
  - name: GigabitEthernet2
    description: to_CSR-2_Gig1
  - name: GigabitEthernet3
    description: to_CSR-3_Gig1

intf_duplex: full
intf_mtu: 1500