---

## First Play - uses 'ios_command' module to show ios version running on the hosts

- hosts: CSR_Routers

  tasks:
    - name: "Show Version"
      ios_command:
        commands: show version
      register: version
    - debug:
        var: version.stdout[0]

    - name: "Save output to a file in ./ansible-roger/"
      copy:
        content: "{{version.stdout[0]}}"
        dest: "/home/device-backups/cisco/{{inventory_hostname}}-version.txt"
