---

# Play 1 - this play configure Layer 2 interfaces parameters such as
#description, MTU, state etc. on the CSR-Routers

- hosts: CSR_Routers
  become: yes

  tasks:          # this task was successful using the loop
    - name: "Task 2 - configure interface parameters"
      ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
            duplex: "{{ intf.duplex }}"
            mtu: "{{ intf.mtu }}"
      loop: "{{ interfaces[inventory_hostname] }}"

    - name: "Save config"
      ios_command:
        commands: copy running-configuration startup-configuration
