---

# Play 1 - this play configure Layer 2 interfaces parameters such as
#description, MTU, state etc. on the CSR-Routers

- hosts: CSR_Routers
  become: yes

  tasks:          # this task was successful using the loop
    - name: "Task - configure interface parameters on all CSR Routers"
      ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
            duplex: "{{ intf_duplex }}"
            mtu: "{{ intf_mtu }}"
      loop: "{{ interfaces[inventory_hostname] }}"