---
## Play 1 - this play configure Layer 3 interfaces on the CSR-Routers

- hosts: CSR_Routers
  become: yes
  vars:
    vlan200: "200"

  tasks:
    - name: "Task 1 configure interfaces settings"
      ios_config:
        lines:
          - vlan "{{ vlan200 }}"
