---
## Play 1 - this play configure Layer 3 interfaces on the CSR-Routers

- hosts: CSR-1

  tasks:
    - name: "Task 1 - configure interfaces settings"
      ios_config:
        lines:
          - description "{{ hostvars.hostname.description }}"
          - ip address "{{ hostvars.hostname.ip }}"
        parents: "{{ hostvars.hostname.interfaces.name }}"




