---

# Play 1 - this play configure Layer 3 interfaces on the CSR-Routers

- hosts: CSR_Routers
  become: yes

  tasks:          # this task was successful using the loop
    - name: "Task 1 - configure interfaces IPs"
      ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
            - address: "{{ item.ipv4 }}"
      loop: "{{ l3_interfaces[inventory_hostname] }}" #list needs to be looped over

    - name: "Tasks 2 - configure loopback interfaces"
      ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
            - address: "{{ item.ipv4 }}"
      loop: "{{ l3_interfaces[inventory_hostname] }}"
      when: "'Loopback' in the item.name"
      tags: loopback
