---
## Play 1 - this play configure Layer 3 interfaces on the CSR-Routers

- hosts: CSR_Routers
  become: yes

  tasks:
    - name: "Task 1 configure interfaces settings"
      ios_config:
        lines:
          - ip address {{ interfaces.ip }} {{ interfaces.mask }}
        parents: interface {{ interfaces.name }}
