---
## Play 1 - this play configure Layer 3 interfaces on the CSR-Routers

- hosts: CSR_Routers

  tasks:
    - name: 'Task 1 - configure interfaces settings'
      ios_interfaces:
        config:
          - name       : "{{ interfaces.interface1 }}"
            description: "Data"
            enabled    : True
          - name       : "{{ interfaces.interface2 }}"
            description: "Mgmt"
            mtu        : 2800
            enabled    : False
            speed      : 100

    - name: 'Task2: Configure layer 3 interfaces'
      ios_l3_interfaces:
        config:
          - name       : "{{ interfaces.interface2 }}"
            ipv4:
            - address: 10.10.1."{{ hostname.hostnumber }}"

