---
## Play 1 - this play configure Layer 3 interfaces on the CSR-Routers

- hosts: CSR-1

  var:
    - name: GigabitEthernet1
    - description: to_CSR-2_Gig1
    - ip: 10.0.12.1
    - mask: 255.255.255.0
  tasks:
    - name: "Task 1 configure interfaces settings"
      ios_config:
        lines:
          - description "{{ description }}"
          - ip address "{{ ip }}" "{{ mask }}"
        parents: "{{ name }}"




