---

- name: "Play - configure basic system settings such as hostname, domain, NTP etc."
  hosts: CSR_Routers
  ansible_become: yes

  tasks:
    - name: "Task 1 - Configure hostname, domain"
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"

    - name: "Task 2 - configure name servers"
      ios_system:
        name_servers: "{{ item.ip }}"
      loop: "{{ name_servers }}"
