---
## Play 1 - this play configure Layer 3 interfaces on the CSR-Routers

- hosts: CSR_Routers

  tasks:
    - name: "Task 1 - configure interfaces settings"
      ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
            enabled: True
      loop: "{{ interfaces[inventory_hostname] }}"

    - name: "Task2: Configure layer 3 interfaces"
      ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
            - address: "{{ item.ip }}"
      loop: "{{ interfaces[inventory_hostname] }}"



